# Generated by Django 6.0.1 on 2026-01-28 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, default='image/events.jpeg', max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(choices=[('DHAKA', 'Dhaka'), ('SYLHET', 'Sylhet'), ('CHOTTOGRAM', 'Chottogram'), ('RAJSHAHI', 'Rajshahi'), ('MYMENSINGH', 'Mymensingh'), ('RANGPUR', 'Rangpur'), ('KHULNA', 'Khulna'), ('BARISHAL', 'Barishal')], default='DHAKA', max_length=250)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.category')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('events', models.ManyToManyField(blank=True, related_name='participants', to='events.event')),
            ],
        ),
    ]
